<?php

declare(strict_types=1);
require_once __DIR__.'/initiative-common.php';require_once __DIR__.'/../includes/layout.php';
$uid=initiativeUserId();$id=(int)($_GET['id']??0);$i=initiativeLoad($id);initiativeRequireView($i,$uid);$db=initiativeDb();
$s=$db->prepare("SELECT ip.*,u.email FROM initiative_participants ip JOIN users u ON u.user_id=ip.user_id WHERE ip.initiative_id=:id ORDER BY u.email");$s->execute(['id'=>$id]);$participants=$s->fetchAll();
$s=$db->prepare("SELECT u.user_id,u.email FROM users u WHERE u.is_active=TRUE AND u.user_id<>:uid ORDER BY u.email LIMIT 500");$s->execute(['uid'=>$uid]);$users=$s->fetchAll();
$s=$db->prepare("SELECT rr.*,u.email requested_by_email FROM initiative_revision_rounds rr JOIN users u ON u.user_id=rr.requested_by WHERE rr.initiative_id=:id ORDER BY rr.round_number DESC");$s->execute(['id'=>$id]);$rounds=$s->fetchAll();
$s=$db->prepare("SELECT rn.*,u.email FROM initiative_revision_notes rn JOIN initiative_revision_rounds rr ON rr.revision_round_id=rn.revision_round_id JOIN users u ON u.user_id=rn.author_id WHERE rr.initiative_id=:id ORDER BY rn.created_at");$s->execute(['id'=>$id]);$notes=$s->fetchAll();$notesBy=[];foreach($notes as $note)$notesBy[(int)$note['revision_round_id']][]=$note;
$s=$db->prepare("SELECT e.*,u.email FROM initiative_events e LEFT JOIN users u ON u.user_id=e.actor_id WHERE e.initiative_id=:id ORDER BY e.created_at DESC LIMIT 100");$s->execute(['id'=>$id]);$events=$s->fetchAll();
$s=$db->prepare("SELECT wis.*,p.name position_name,ou.name unit_name FROM workflow_instances wi JOIN workflow_instance_steps wis ON wis.workflow_instance_id=wi.workflow_instance_id LEFT JOIN positions p ON p.position_id=wis.assigned_position_id LEFT JOIN organizational_units ou ON ou.unit_id=wis.assigned_unit_id WHERE wi.entity_type='INITIATIVE' AND wi.entity_id=:id ORDER BY wi.started_at DESC,wis.step_order");$s->execute(['id'=>$id]);$steps=$s->fetchAll();
$canEdit=initiativeCanEdit($i,$uid);$canDecide=initiativeCanDecide($id,$uid);$canManage=initiativeCanManageParticipants($i,$uid);$canConvert=(string)$i['status']==='APPROVED'&&initiativeUserHasRole($uid,'Initiative Approver');$open=initiativeOpenRevision($id);
workspaceHeader((string)$i['title'],'initiatives');?>
<section class="workspace-page-header"><div><p class="eyebrow mb-2">Initiative request</p><h1 class="h2 mb-2"><?=initiativeH($i['title'])?></h1><p class="text-secondary mb-0"><?=initiativeH($i['initiative_code']??'Not converted yet')?> · <?=initiativeH(str_replace('_',' ',$i['status']))?></p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="initiative-module/initiative-dashboard.php">Back</a><?php if($canEdit):?><a class="btn btn-primary" href="initiative-module/initiative-edit.php?id=<?=$id?>">Edit</a><?php endif;?></div></section>
<div class="row g-4"><div class="col-xl-8"><section class="workspace-card mb-4"><div class="workspace-card-header"><h2 class="h5 mb-1">Request information</h2></div><div class="form-section"><div class="row g-4"><div class="col-md-6"><small class="text-secondary">Type</small><p class="fw-semibold"><?=initiativeH($i['initiative_type']??'—')?></p></div><div class="col-md-6"><small class="text-secondary">Budget</small><p class="fw-semibold"><?=initiativeH($i['expected_budget']!==null?number_format((float)$i['expected_budget'],2):'—')?></p></div><div class="col-12"><h3 class="h6">Description</h3><p class="text-secondary"><?=nl2br(initiativeH($i['description']?:'—'))?></p><h3 class="h6">Objectives</h3><p class="text-secondary mb-0"><?=nl2br(initiativeH($i['objectives']?:'—'))?></p></div></div></div></section>
<section class="workspace-card mb-4"><div class="workspace-card-header"><h2 class="h5 mb-1">Approval path</h2></div><?php if(!$steps):?><div class="form-section text-secondary">Not submitted yet.</div><?php else:?><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Step</th><th>Assigned to</th><th>Unit</th><th>Status</th><th>Comments</th></tr></thead><tbody><?php foreach($steps as $x):?><tr><td><?=(int)$x['step_order']?></td><td><?=initiativeH($x['position_name']?:'Creator')?></td><td><?=initiativeH($x['unit_name']?:'—')?></td><td><?=initiativeH(str_replace('_',' ',$x['status']))?></td><td><?=initiativeH($x['comments']?:'—')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="workspace-card mb-4"><div class="workspace-card-header"><h2 class="h5 mb-1">Revision rounds</h2></div><?php if(!$rounds):?><div class="form-section text-secondary">No revisions requested.</div><?php else:?><div class="form-section"><?php foreach($rounds as $r):?><div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>Round <?=(int)$r['round_number']?></strong><span class="badge text-bg-light"><?=initiativeH($r['status'])?></span></div><p class="mt-2 mb-2"><?=nl2br(initiativeH($r['request_comments']))?></p><?php foreach($notesBy[(int)$r['revision_round_id']]??[] as $note):?><div class="bg-light rounded p-2 mb-2"><small class="fw-semibold"><?=initiativeH($note['email'])?></small><div><?=nl2br(initiativeH($note['note_text']))?></div></div><?php endforeach;?></div><?php endforeach;?></div><?php endif;?><?php if($open):?><form method="post" action="initiative-module/revision-action.php" class="form-section border-top"><input type="hidden" name="csrf" value="<?=initiativeCsrf()?>"><input type="hidden" name="initiative_id" value="<?=$id?>"><label class="form-label">Add revision discussion note</label><textarea class="form-control" name="note" required></textarea><button class="btn btn-primary mt-3">Add note</button></form><?php endif;?></section>
<section class="workspace-card"><div class="workspace-card-header"><h2 class="h5 mb-1">Event history</h2></div><div class="list-group list-group-flush"><?php foreach($events as $e):?><div class="list-group-item px-4 py-3"><div class="d-flex justify-content-between"><strong><?=initiativeH(str_replace('_',' ',$e['event_type']))?></strong><small class="text-secondary"><?=initiativeH((string)$e['created_at'])?></small></div><small class="text-secondary"><?=initiativeH($e['email']?:'System')?></small></div><?php endforeach;?></div></section></div>
<div class="col-xl-4"><section class="workspace-card mb-4"><div class="workspace-card-header"><h2 class="h5 mb-1">Actions</h2></div><form method="post" action="initiative-module/initiative-action.php" class="form-section"><input type="hidden" name="csrf" value="<?=initiativeCsrf()?>"><input type="hidden" name="initiative_id" value="<?=$id?>"><?php if($canEdit):?><button class="btn btn-primary w-100 mb-3" name="action" value="submit">Submit / resubmit</button><?php endif;?><?php if($canDecide):?><textarea class="form-control mb-3" name="comments" placeholder="Decision comments"></textarea><div class="d-grid gap-2"><button class="btn btn-success" name="action" value="approve">Approve</button><button class="btn btn-outline-warning" name="action" value="request_changes">Request changes</button><button class="btn btn-outline-danger" name="action" value="reject">Reject</button></div><?php endif;?></form><?php if($canConvert):?><form method="post" action="initiative-module/convert-action.php" class="form-section border-top"><input type="hidden" name="csrf" value="<?=initiativeCsrf()?>"><input type="hidden" name="initiative_id" value="<?=$id?>"><button class="btn btn-dark w-100">Convert to active initiative</button></form><?php endif;?></section>
<section class="workspace-card"><div class="workspace-card-header"><h2 class="h5 mb-1">Participants</h2></div><div class="list-group list-group-flush"><?php foreach($participants as $p):?><div class="list-group-item px-4 py-3"><strong><?=initiativeH($p['email'])?></strong><small class="d-block text-secondary"><?=initiativeH($p['participant_role'])?></small><?php if($canManage):?><form method="post" action="initiative-module/participants-action.php" class="mt-2"><input type="hidden" name="csrf" value="<?=initiativeCsrf()?>"><input type="hidden" name="initiative_id" value="<?=$id?>"><input type="hidden" name="participant_user_id" value="<?=(int)$p['user_id']?>"><button class="btn btn-sm btn-outline-danger" name="action" value="remove">Remove</button></form><?php endif;?></div><?php endforeach;?></div><?php if($canManage):?><form method="post" action="initiative-module/participants-action.php" class="form-section border-top"><input type="hidden" name="csrf" value="<?=initiativeCsrf()?>"><input type="hidden" name="initiative_id" value="<?=$id?>"><label class="form-label">Add participant</label><select class="form-select mb-2" name="participant_user_id" required><option value="">Choose account</option><?php foreach($users as $u):?><option value="<?=(int)$u['user_id']?>"><?=initiativeH($u['email'])?></option><?php endforeach;?></select><input class="form-control mb-2" name="participant_role" value="MEMBER"><button class="btn btn-primary w-100" name="action" value="add">Add participant</button></form><?php endif;?></section></div></div><?php workspaceFooter();?>
